### ISSUE TITLE
Handle nil response

### ISSUE THREAD

**Issue by anton-putau** [progaudi/tarantool-csharp#68]
I am trying to get response from lua function and got exception with nil value (lua function result):

`
var data = (await this.box.Call<TInput, TOutput>("FunctionName", Tuple.Create(.....))).Data;
`
Exception:

`System.ArgumentException : Invalid array length: 3 is expected, but got 1.
   at Tarantool.Client.LogicalConnection.<SendRequestImpl>d__112.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tarantool.Client.LogicalConnection.<SendRequest>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tarantool.Client.Box.<Call>d__82.MoveNext()`

Expected behavior `Data = empty array`

**Comment by aensidhe** [comment]
Won't fix. Nils in lua are broken. 

 msgpack.NULL
